{
 "title": "Graficas",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Carga del Sistema (1 Minuto)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de CPU Promedio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafico de red - salida",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafico de red - entrada",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}